### ISSUE TITLE
Start every notebook with `from __future__ import division`

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/skimage-tutorials#16]
We will have people using both Python 2 and Python 3 at tutorial sessions for the forseeable future. This is just prudent to keep us out of trouble.

If a `print` statement is ever used in a cell, it would also be reasonable to import `print_function` in that notebook.

Personally I like this to be cell zero, even before the title, along with `%matplotlib inline`, in the style of scikit-learn.

**Comment by jni** [comment]
:+1: !

Although, I also favour explicitly saying "we will be using Python 3 for this tutorial, and recommend you do the same". Conda makes this process very painless. If you distribute an environment.yml prior to the workshop, you should be able to get everyone on the exact same env as you. Which is, frankly, absolutely amazing.

**Comment by JDWarner** [comment]
True, but the tutorial guidelines state rather clearly that we should plan for a very heterogeneous environment. Neither Anaconda nor Conda can be prerequisites.

I'll work on this tomorrow.

**Comment by stefanv** [comment]
+1 for py3 recommendation
