### ISSUE TITLE
RFC: Require IPython/Jupyter >=3.0

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/skimage-tutorials#18]
I upgraded my Anaconda distribution after submitting #17 and noticed IPython/Jupyter is now converting notebooks to a new format. 

We need to decide if we want to

* keep the dependency at 2.0, in which case we must be _extremely careful_ all of our changes are saved and committed only from 2.x 
* require version 3.x, which is backwards compatible with older notebooks

I favor requiring version 3.x. The former is possible, but it's going to be increasingly difficult to support. One accidental save, commit, and merge, and we're in trouble.

This would require modifications to the `check_env.py` script.

**Comment by JDWarner** [comment]
ping @stefanv and @blink1073, also @jni and @tonysyu since all of our lectures are in one place.

**Comment by jni** [comment]
My vote is definitely for 3.x!

**Comment by blink1073** [comment]
3.x all the way.

**Comment by stefanv** [comment]
Afraid I don't have an old version of IPython available.  We can convert notebooks to older versions if need be:  ``ipython nbconvert --to notebook --nb-format=2 file`` or something like that.

**Comment by JDWarner** [comment]
Thanks for your input - the consensus seems to be to use v4 notebooks in the repo. As Stefan mentioned, if needed we can use `nbconvert` to downconvert these to the prior version.
