### ISSUE TITLE
Add a link to nbviewer.jupyter.org to readme

### ISSUE THREAD

**Issue by adius** [scikit-image/skimage-tutorials#24]
http://nbviewer.jupyter.org/github/scikit-image/skimage-tutorials/blob/master/index.ipynb

**Comment by soupault** [comment]
@adius Hi! Feel free to submit a PR.

**Comment by adius** [comment]
I just realized that nbviewer also doesn't support inline mathplotlib images.
So it's actually not better than the renderings already provided by GitHub...
