### ISSUE TITLE
Exception in example code, notebooks/lectures/4_segmentation.ipynb

### ISSUE THREAD

**Issue by mok0** [scikit-image/skimage-tutorials#50]
When working through the tutorial _'Image analysis in Python with SciPy and scikit-image'_, I encountered a problem in the section _Combining regions with a Region Adjacency Graph (RAG)_. When attempting to generate the graph, I get an exception:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-123-d2130ec30b20> in <module>
      6 # Pass centroid data into the graph
      7 for region in regions:
----> 8     rag.node[region['label']]['centroid'] = region['centroid']

AttributeError: 'RAG' object has no attribute 'node'
```

It appears the API has changed since the tutorial was given.

I am using scikit-image version: 0.16.2 (downloaded with pip3 today), IPython version 7.8.0 and Python version 3.7.4.

**Comment by mok0** [comment]
It appears the `node` attribute is called `nodes`. If you change:

```
rag.node[region['label']]['centroid'] = region['centroid']
```

to

```
rag.nodes[region['label']]['centroid'] = region['centroid']
```

and make the same change in the convenience function `display_edges` it appears that the code runs as intended.

**Comment by hmaarrfk** [comment]
would you like to make the PR for it?

**Comment by soupault** [comment]
I suggest to keep this open until it is fixed.
@mok0 thanks for reporting! ☺️

**Comment by mok0** [comment]
I don't think my version of git can handle .ipynb's. I used to have a plugin but it doesn't work anymore. It's a really simple change, just do raw.node -> rag.nodes.
