### ISSUE TITLE
Unsupervised 3D image segmentation 

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [scikit-image/skimage-tutorials#54]
Hi,

Can we do 3D image segmentation using skimage. If Yes, can you please guide me to a few algorithms?

Thank you very much.

**Comment by stefanv** [comment]
Thank you for your interest in scikit-image, @soumya-ranjan-sahoo.  Please visit out user forum at https://forum.image.sc/ and ask your question there.
