### ISSUE TITLE
Removing Brag's peaks from image!

### ISSUE THREAD

**Issue by hkazmi25** [scikit-image/skimage-tutorials#62]
![diffuse scatt_1](https://user-images.githubusercontent.com/60356551/131888466-9f074deb-846f-4f1b-9ef3-f6f53a9feff0.png)
Hi respected Developers!

In above image you see red dots are the brags peaks from electron diffraction simulation in an ideal crystal(image 512x512).  I wanted to remove dominant these red spots( called brags peaks ) so that i can see only diffuse scattering(background) in my images.  The problem is intensity of diffuse scattering is quite low as comparing to brags peaks , that can be only be seen by plotting this image at low intensity limit,(so when i try to reduce the intensity, brags peaks becomes so dominant that i almost lost the information of diffuse scattering from background,hence therefore) would it be possible that i can somehow able to mask  those red dots and remove these brags diffraction peaks and see the only diffuse patterns in background,  can any one walk me through this (i am not pro in python).? I shall be very grateful for this!

Thanks

**Comment by stefanv** [comment]
Dear @hkazmi25, thank you for your question.  Would you kindly repost your question to https://forum.image.sc/? That is our official "support channel". Thanks!
